<?php

if( function_exists('acf_add_local_field_group') ):

    acf_add_local_field_group(array(
        'key' => 'group_5ffc42e0ab235',
        'title' => 'Page Builder',
        'fields' => array(
            array(
                'key' => 'field_5ffc43074a490',
                'label' => '<span class="mdi mdi-console" ></span> Page Builder',
                'name' => '',
                'type' => 'tab',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'placement' => 'top',
                'endpoint' => 0,
            ),
            array(
                'key' => 'field_5ffc43724a491',
                'label' => 'Builder Instance',
                'name' => 'builder_instance',
                'type' => 'repeater',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'collapsed' => 'field_5ffc43a04a492',
                'min' => 0,
                'max' => 0,
                'layout' => 'block',
                'button_label' => 'Add Section',
                'sub_fields' => array(
                    array(
                        'key' => 'field_5ffc43a04a492',
                        'label' => 'Title',
                        'name' => 'title',
                        'type' => 'text',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'default_value' => '',
                        'placeholder' => '',
                        'prepend' => '',
                        'append' => '',
                        'maxlength' => '',
                    ),
                    array(
                        'key' => 'field_5ffc43ac4a493',
                        'label' => 'Organism',
                        'name' => 'organism',
                        'type' => 'flexible_content',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'layouts' => array(
                            'layout_5ffc43e55cfab' => array(
                                'key' => 'layout_5ffc43e55cfab',
                                'name' => 'rawcode',
                                'label' => '<span class="mdi mdi-microsoft-visual-studio-code"></span> Raw Code',
                                'display' => 'block',
                                'sub_fields' => array(
                                    array(
                                        'key' => 'field_5ffc51ff74345',
                                        'label' => '',
                                        'name' => 'rawcode',
                                        'type' => 'clone',
                                        'instructions' => '',
                                        'required' => 0,
                                        'conditional_logic' => 0,
                                        'wrapper' => array(
                                            'width' => '',
                                            'class' => '',
                                            'id' => '',
                                        ),
                                        'clone' => array(
                                            0 => 'group_5ffc51875a17b',
                                        ),
                                        'display' => 'seamless',
                                        'layout' => 'block',
                                        'prefix_label' => 0,
                                        'prefix_name' => 0,
                                    ),
                                ),
                                'min' => '',
                                'max' => '',
                            ),
                            'layout_5ffc6942a4e5d' => array(
                                'key' => 'layout_5ffc6942a4e5d',
                                'name' => 'flickity',
                                'label' => '<span class="mdi mdi-table-row"></span> Flickity',
                                'display' => 'block',
                                'sub_fields' => array(
                                    array(
                                        'key' => 'field_5ffc6956a4e5e',
                                        'label' => '',
                                        'name' => 'flickity',
                                        'type' => 'clone',
                                        'instructions' => '',
                                        'required' => 0,
                                        'conditional_logic' => 0,
                                        'wrapper' => array(
                                            'width' => '',
                                            'class' => '',
                                            'id' => '',
                                        ),
                                        'clone' => array(
                                            0 => 'group_5ffc654aaac1c',
                                        ),
                                        'display' => 'seamless',
                                        'layout' => 'block',
                                        'prefix_label' => 0,
                                        'prefix_name' => 0,
                                    ),
                                ),
                                'min' => '',
                                'max' => '',
                            ),
                            'layout_5ffd87c36b115' => array(
                                'key' => 'layout_5ffd87c36b115',
                                'name' => 'isotope',
                                'label' => '<span class="mdi mdi-table"></span> Isotope',
                                'display' => 'block',
                                'sub_fields' => array(
                                    array(
                                        'key' => 'field_5ffd87d26b116',
                                        'label' => '',
                                        'name' => 'isotope',
                                        'type' => 'clone',
                                        'instructions' => '',
                                        'required' => 0,
                                        'conditional_logic' => 0,
                                        'wrapper' => array(
                                            'width' => '',
                                            'class' => '',
                                            'id' => '',
                                        ),
                                        'clone' => array(
                                            0 => 'group_5ffd803e128fe',
                                        ),
                                        'display' => 'seamless',
                                        'layout' => 'block',
                                        'prefix_label' => 0,
                                        'prefix_name' => 0,
                                    ),
                                ),
                                'min' => '',
                                'max' => '',
                            ),
                            'layout_6007e4d9fbe17' => array(
                                'key' => 'layout_6007e4d9fbe17',
                                'name' => 'yt_lite',
                                'label' => '<span class="mdi mdi-youtube"></span> YouTube-Lite',
                                'display' => 'block',
                                'sub_fields' => array(
                                    array(
                                        'key' => 'field_6007e4f1fbe18',
                                        'label' => '',
                                        'name' => 'yt_lite',
                                        'type' => 'clone',
                                        'instructions' => '',
                                        'required' => 0,
                                        'conditional_logic' => 0,
                                        'wrapper' => array(
                                            'width' => '',
                                            'class' => '',
                                            'id' => '',
                                        ),
                                        'clone' => array(
                                            0 => 'group_6007e242e0872',
                                        ),
                                        'display' => 'seamless',
                                        'layout' => 'block',
                                        'prefix_label' => 0,
                                        'prefix_name' => 0,
                                    ),
                                ),
                                'min' => '',
                                'max' => '',
                            ),
                        ),
                        'button_label' => 'Add Organism',
                        'min' => '',
                        'max' => '',
                    ),
                ),
            ),
            array(
                'key' => 'field_5ffc5d2259b94',
                'label' => '<span class="mdi mdi-cog"></span> Settings',
                'name' => '',
                'type' => 'tab',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'placement' => 'top',
                'endpoint' => 0,
            ),
            array(
                'key' => 'field_600577ea9294e',
                'label' => 'Body Classes',
                'name' => 'body_classes',
                'type' => 'text',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'default_value' => '',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'maxlength' => '',
            ),
            array(
                'key' => 'field_600577085522f',
                'label' => 'Page Classes',
                'name' => 'page_classes',
                'type' => 'text',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'default_value' => '',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'maxlength' => '',
            ),
            array(
                'key' => 'field_600587fc6ac51',
                'label' => '<span class="mdi mdi-svg"></span> SVGs',
                'name' => '',
                'type' => 'tab',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'placement' => 'top',
                'endpoint' => 0,
            ),
            array(
                'key' => 'field_600588176ac52',
                'label' => 'Svg Instances',
                'name' => 'svg_instances',
                'type' => 'repeater',
                'instructions' => 'Add SVGs into the footer. Make sure that it is a "symbol" so you can reference it in the page.',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'collapsed' => '',
                'min' => 0,
                'max' => 0,
                'layout' => 'block',
                'button_label' => '',
                'sub_fields' => array(
                    array(
                        'key' => 'field_6005882c6ac53',
                        'label' => 'SVG',
                        'name' => 'svg',
                        'type' => 'textarea',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '',
                            'class' => 'ue__codemirror',
                            'id' => '',
                        ),
                        'default_value' => '<svg xmlns="http://www.w3.org/2000/svg" style="width:0;height:0;visibility:hidden;">
        <symbol viewBox="0 0 24 24" id="transfer-right">
            <path d="M3,8H5V16H3V8M7,8H9V16H7V8M11,8H13V16H11V8M15,19.25V4.75L22.25,12L15,19.25Z"/>
        </symbol>
    </svg>',
                        'placeholder' => '',
                        'maxlength' => '',
                        'rows' => 4,
                        'new_lines' => '',
                    ),
                ),
            ),
        ),
        'location' => array(
            array(
                array(
                    'param' => 'post_type',
                    'operator' => '==',
                    'value' => 'page',
                ),
            ),
        ),
        'menu_order' => 0,
        'position' => 'acf_after_title',
        'style' => 'default',
        'label_placement' => 'top',
        'instruction_placement' => 'label',
        'hide_on_screen' => array(
            0 => 'the_content',
        ),
        'active' => true,
        'description' => '',
    ));
    
    endif;